version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./client
  docker-build:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stochel/cicd-server:$TAG .
            docker push stochel/cicd-server:$TAG
          working_direcory: ./server
      - run:
          command: |
            TAG=0.1$.CIRCLE_BUILD_NUM
            docker build -t stochel/cicd-client:$TAG .
            docker push stochel/cicd-client:$TAG
          working_direcory: ./client
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - docker-build
